### ISSUE TITLE
Prior data added with repeated runs

### ISSUE THREAD

**Issue by awilson77584** [adejoux/nmon2influxdb#32]
The work you have added is a major leap forward. The ability to sample data via the HMC is exactly what we needed. Thx!

It appears that when nmon2influxdb runs against the same directory it loads all of the data in the directory rather than the delta from the last run.  Is that purposeful?  The earlier version used the nmon2influxdb_log db to checkpoint the prior run and start from there.

If the current design will process all of the files in the directory, we can adjust our approach and move them out after processing so we won't get duplicated data.  We use rsync to copy the delta from the prior {x} minutes so that the user can have a near-realtime view.

Thanks!
Alan

**Comment by adejoux** [comment]
Hello,

I will check this issue. I planned to have partial import for directories too. I need regression testing for this part. It's not the first time I had issue here. Last time, it was related to go version upgrade(but the original fault was a wrong assumption on my part :) ).

Thanks

**Comment by adejoux** [comment]
Hello,

 I couldn't reproduce the problem. 
When processing this directory:

````
adejoux@alains-MBP:~/go/src/github.com/adejoux/nmon2influxdb/samples|master⚡ 
⇒  ls
aixlpar.nmon.gz           linux_150818_1024.nmon.gz vios1_150706_1552.nmon.gz vios2_150706_1327.nmon.gz
`````
I have the expected behavior:

![image](https://cloud.githubusercontent.com/assets/741174/20807122/ef57ec92-b7fd-11e6-9278-ceba80787d21.png)

In nmon2inflxudb_log database, I have the corresponding entries:

![image](https://cloud.githubusercontent.com/assets/741174/20807173/1f52915e-b7fe-11e6-8ac1-3318e64ccc29.png)


Can you check in nmon2influxdb_log if you have entries?

Thanks,

Alain

**Comment by awilson77584** [comment]
I posted this based upon a misunderstanding of the output.  The checksum values are in the nmon2influxdb_log database.  I apologize.  Please close this.

Thanks!

**Comment by adejoux** [comment]
No problem. And a big thanks for all your inputs :)
