### ISSUE TITLE
where can find the nmon2influxdblib.Config?

### ISSUE THREAD

**Issue by chiangtsungi** [adejoux/nmon2influxdb#64]
Hi,
I run nmon2influxdb_2.1.6_linux_64-bit on RHEL 7, but showed the error message as the below, I can't find the nmon2influxdblib.Config, where can find this file?
syntax error in configuration file: line 10: field corresponding to `grafana_url' is not defined in nmon2influxdblib.Config

**Comment by adejoux** [comment]
Hello,

It's because some parameters changed in last versions of nmon2influxdb. It was introduced to be more consistent. Sorry for the problem.

You have two solutions:
- rename grafana_url to grafana_URL in ~/.nmon2influxdb.cfg file 
- rename ~/.nmon2influxdb.cfg to ~/.nmon2influxdb.cfg_OLD and run nmoN2inflxudb again. It will generate a new ~/.nmon2influxdb.cfg file with the correct paremeters but you will need to aply your settings again. 


regards,

Alain

**Comment by chiangtsungi** [comment]
It's work, Thank you!
